- coopy/DiffRender.hx
I'm not very sure about this commit. I haven't installed Haxe to test this, and it's less trivial than the other ones. 
Please test before merging.
> DiffRender: put the header and the body of the table in appropriate HTML tags

- coopy/Coopy.hx
Occasionally git will pass daff an extra 2 arguments
when using it as a diff driver. This commit (1) stops
daff from freaking out completely and (2) passes on
a helpful description of the change from git.
Fixes #29. Thanks @tsibley for looking into this.
> teach daff about file moves/renames

- coopy/HighlightPatch.hx
- coopy/SqlCompare.hx
- coopy/SqlHelper.hx
- coopy/SqlTable.hx
- coopy/SqliteHelper.hx
- env/js/sqlite_database.js
- env/py/sqlite_database.py
- harness/SqlTest.hx
This implements patching an sqlite table, using a daff-generated diff. It avoids loading the full table into memory, with all operations offloaded to sql.
> flesh out patching of sqlite tables

- coopy/Alignment.hx
- coopy/CompareFlags.hx
- coopy/CompareTable.hx
- coopy/Coopy.hx
- coopy/Ordering.hx
- coopy/SimpleTable.hx
- coopy/SimpleView.hx
- coopy/SqlCompare.hx
- coopy/TableDiff.hx
- env/js/util.js
- harness/BasicTest.hx
- harness/MergeTest.hx
- harness/Native.hx
- harness/SqlTest.hx
- scripts/tester.js
- test/test_3way_alignment.js
- test/test_column_alignment.js
- test/test_sqlite.py
This completes sql-based diffs between tables for which a common ancestor is known.  It also makes some fixes so that the content of sql tables need not to be loaded into memory in order to correctly render the diffs.
> implement 3-way comparison for sqlite

- coopy/CellBuilder.hx
- coopy/CompareFlags.hx
- coopy/FlatCellBuilder.hx
- coopy/NestedCellBuilder.hx
- coopy/TableDiff.hx
- coopy/Unit.hx
- test/data/bridges_diff_add_column_ncol.html
- test/data/bridges_diff_show_index_ncol.html
- test/test_hilite_render.js
The `--index` option to daff gives row/column numbers. Column numbers don't actually make much sense as integers, since users are rarely exposed to them in that form. In spreadsheets, they see column numbering like `A,B,...,AA,AB,...`.  This commit switches daff's default to that notation.  `CompareFlags` now has an extra `count_like_a_spreadsheet` flag that can be turned off if original behavior is desired. Inspired by @jordigh in dataprotocols/dataprotocols#162
> switch default numbering of columns to base 26, excel style

- .travis.yml
- coopy/CompareFlags.hx
- coopy/CompareTable.hx
- coopy/Coopy.hx
- coopy/Index.hx
- coopy/IndexPair.hx
- coopy/TableDiff.hx
- harness/Main.hx
- harness/WhiteSpaceTest.hx
This adds an `--ignore-whitespace`/`-w` flag that treats cells that differ only in leading or trailing whitespace as identical.
> implement --ignore-whitespace / -w flag, see #36

- coopy/Alignment.hx
- coopy/CompareFlags.hx
- coopy/CompareTable.hx
- coopy/Coopy.hx
- coopy/Meta.hx
- coopy/SimpleMeta.hx
- coopy/SimpleView.hx
- coopy/SqlCompare.hx
- coopy/SqlTable.hx
- coopy/SqlTables.hx
- coopy/SqliteHelper.hx
- coopy/TableComparisonState.hx
- coopy/TableDiff.hx
- coopy/Tables.hx
- coopy/View.hx
- env/php/PhpCellView.class.php
So far sqlite diffs have been restricted to a single table. This removes that limitation, providing useful diffs for multi-table changes, addition of tables, and removal of tables.
> implement multi-table comparison for sqlite sources

- coopy/TerminalDiffRender.hx
When generating colorful, human-friendly diffs, we try to add sane
spacing between columns.  This commit improves the spacing in the
presence of occasional cells that are unusually long.
> improve column alignment on colored diffs with occasional long cells

- coopy/CompareFlags.hx
- coopy/Coopy.hx
- coopy/TerminalDiffRender.hx
daff learns `--padding sparse`, `--padding dense`, and `--padding smart` for controlling alignment in colorful diffs.
> allow padding strategy to be controlled from command line

- coopy/Csv.hx
- harness/BasicTest.hx
Prior to this, a CSV file with a row that had more cells
than others would result in silently mis-reading the entire
table.  With this change, such cells are ignored, and the
user is warned (if the cells are non-blank).
Thanks @paulsaurels for reporting a case of this.
> parse csv with rows of unexpected length in saner way

- env/js/util.js
See https://github.com/nodejs/node-v0.x-archive/issues/1918
Thanks @paulsaurels for reporting a case of this.
> strip BOM marker when loading utf8 text

- coopy/Coopy.hx
- coopy/DiffRender.hx
- coopy/JsonTable.hx
- coopy/JsonTables.hx
This adds a basic wrapper for diffing multiple tables
expressed as json in the following form:
```js
{
"names": ["sheet1", "sheet2"],
"tables": {
"sheet1": {
"columns": ["col1", "col2", "col3"],
"rows": [
{ "col1": 42, "col2": "x", "col3": null },
{ "col1": 24, "col2": "y", "col3": null },
...
]
},
"sheet2": {
...
}
}
}
```
> teach daff to diff workbooks expressed in json

- coopy/CompareFlags.hx
- coopy/Coopy.hx
- coopy/Index.hx
- coopy/TableDiff.hx
- harness/EqualityTest.hx
- harness/Main.hx
This adds a `-i` / `--ignore-case` flag that works in a similar way to `diff -i`, with cells that differ only in case being treated as identical.
Case is a complex subject so depending on your language your mileage may vary.
Motivated by https://twitter.com/thmchx/status/661951143967383552
> add flag for ignoring case during comparison

- .travis.yml
The official ppa is guaranteed to provide updated release of Haxe. It currently provides Haxe 3.2.1.
Eyecreate's one provides Haxe 3.2.0.
daff is an excellent use of Haxe. 
Keep it up! : )
> use the ppa provided by haxe foundation

- coopy/Coopy.hx
- coopy/JsonTable.hx
- coopy/JsonTables.hx
- coopy/TableDiff.hx
This is sufficient to make diffs of multi-table json or sqlite sources readable when output in html format.
> fix html-format diffs of nested tables

- coopy/CompareFlags.hx
- coopy/Coopy.hx
- coopy/TableIO.hx
- env/js/util.js
When using daff as a library, the command for generating terminal
output didn't cope well with multi-table diffs.  This commit
brings this command into line with the output of the command-line
daff utility.
> make ansi output available to library match command-line utility

- coopy/Coopy.hx
- test/test_file_types.js
HTML output was accidentally being overwritten with empty output. This adds a fix and a test so it doesn't happen again. Thanks @spaceman-cb for the heads up.
> don't clobber html output, fixes #66

- coopy/CompareFlags.hx
- coopy/Coopy.hx
- coopy/TerminalDiffRender.hx
Give a simple workaround for terminals where utf8 symbols in diff are causing problems, see #69.
> support --plain flag that suppresses use of utf8 glyphs

- Makefile
- scripts/python23.py
Haxe doesn't support python2 so we play some games to backport from python3.  Update those games for latest haxe, and also to resolve #72.
> update python2 conversion to work with latest haxe

- coopy/Coopy.hx
This is related to the issue https://github.com/paulfitz/daff/issues/75.
> Find daff at `exports` first in javascript

- Makefile
- scripts/python23.py
Haxe doesn't support python2, so we use the 3to2 utility to make haxe-generated python usable in python2.  Then we patch things up to make the same code still runnable in python3.  This code updates those patches for latest haxe.  This is getting a little creaky, and it will soon be preferable to publish a wheel
with multiple distinct code versions for different python flavors.
Motivated by #82.
> update python2 fixes for latest haxe

- Makefile
- coopy/Coopy.hx
- coopy/Csv.hx
- coopy/TerminalDiffRender.hx
- scripts/python23.py
- setup.py
This adds support for the psv format.  This is not easy in javascript due to the poop symbol lying on an astral plane, so for now I've focused on getting it right in python.
Now allow `daff foo.bar` to be used instead of `daff copy foo.bar`, for convenience.
Small cleanup to the python install rat's-nest.
See https://twitter.com/j4mie/status/804701143171497984
> add support for psv

- coopy/TableDiff.hx
- harness/BasicTest.hx
I get an error when trying to compare two tables in Python with all rows shown:
```python
import daff
local = [[0], [1]]
remote = [[0], [2]]
flags = daff.CompareFlags()
flags.show_unchanged = True
table = daff.diff(local, remote, flags)
```
```
/home/sviatoslav/workspace/py34/bin/daff.py in hiliteSingle(self, output)
8344                 dummy = False
8345                 if (out == 1):
-> 8346                     self.publish = ((self.active_row[i] if i >= 0 and i < len(self.active_row) else None) > 0)
8347                     dummy = ((self.active_row[i] if i >= 0 and i < len(self.active_row) else None) == 3)
8348                     if (dummy and showed_dummy):
TypeError: unorderable types: NoneType() > int()
```
So I added a check if row is null.
> Python: Fix comparison to None when 'show_unchanged' is set

- coopy/CompareTable.hx
- coopy/DiffSummary.hx
- coopy/Mover.hx
- coopy/TableDiff.hx
- harness/BasicTest.hx
After `TableDiff.hilite` has been used to produce a diff, the `getSummary` method can be called to get an overall summary of what changed, including counts of row insertions, deletions, etc.
Motivated by https://github.com/paulfitz/daff/issues/87.  Does this look like it would meet your need @gwarnes-mdsol?
> add TableDiff.getSummary() for summary stats of diff

- .travis.yml
- coopy/Csv.hx
- coopy/TerminalDiffRender.hx
A report from @rversteegen showed some inefficiencies.  There
may be multiple sources, but the clearest one in python2 is
on output, where there's some text concatenation going on.
This commit speeds that process up.
https://github.com/paulfitz/daff/issues/53#issuecomment-355704525
> speed up rendering of output

- Makefile
- coopy/Coopy.hx
- env/js/fix_exports.js
- env/js/fix_exports_some_more.js
- env/js/ndjson_table_view.js
- env/js/sqlite_database.js
- env/js/table_view.js
- env/js/util.js
Currently it takes some fiddling around to make daff work with
webpack.  After this change, it gets a lot smoother, so something
like this works:
```js
import daff from 'daff/lib/core';
function testDaff() {
const data1 = [
['Country','Capital'],
['Ireland','Dublin'],
['France','Paris'],
['Spain','Barcelona']
];
const data2 = [
['Country','Code','Capital'],
['Ireland','ie','Dublin'],
['France','fr','Paris'],
['Spain','es','Madrid'],
['Germany','de','Berlin']
];
const alignment = daff.compareTables(data1, data2).align();
const diff = new daff.TableView([]);
const highlighter = new daff.TableDiff(alignment, new daff.CompareFlags());
highlighter.hilite(diff);
return new daff.DiffRender().render(diff).html();
}
function component() {
const element = document.createElement('div'); …
```
> make daff easier to use from webpack

- coopy/CompareFlags.hx
- coopy/Coopy.hx
- coopy/TableDiff.hx
- harness/BasicTest.hx
Currently it is possible to independently specify whether to include inserted, deleted, or updated rows in a diff with the `--act` flag. But if a column is inserted, there's no way to control whether the cells added to each row are included in the diff or not.  Currently, they are somewhat randomly included in the `update` category.  This diff breaks them out as independently controllable.
So to include all changes but the cells of inserted columns, it would suffice to do:
```
daff --act update --act insert --act delete v1.csv v2.csv
```
See #118.
> allow inserted cells from a new column to be controlled separately

- coopy/SimpleView.hx
- coopy/TableDiff.hx
- env/php/PhpCellView.class.php
- harness/BasicTest.hx
Some old code was deliberately sloppy about distinguishing blank strings and nulls, inheriting an ambiguity from csv. This tightens this up, and adds tests.  Fixes #96.
> distinguish blanks and nulls when generating diffs

- coopy/Coopy.hx
See #93.  Now setting `--context-columns 0` can reduce noise in a diff for a table with large numbers of columns.
> expose a flag for controlling number of context columns

- .travis.yml
- README.md
- package-lock.json
- package.json
Adding daff (@1.3.36) yields the following warning from npm (and also via `npm audit`).
```
=== npm audit security report ===
┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Moderate      │ Prototype pollution                                          │ …
```
> update optional deps

- coopy/CompareTable.hx
- coopy/TerminalDiffRender.hx
- test/data/wide1.csv
- test/data/wide2.csv
- test/test_padding.js
Wide diffs currently are rendered densely (without padding) even if the 'sparse' option is set.  This change makes sure that this option is respected.  See #125.
> test wide sparse diffs, and fix them

- coopy/CompareFlags.hx
- coopy/CompareTable.hx
- coopy/Coopy.hx
- coopy/SqlCompare.hx
- coopy/SqlTables.hx
- env/py/sqlite_database.py
- harness/SqlTest.hx
- test/integration_sqlite.sh
Now the --table flag can be --table name1:name2 to allow a table
called name1 to be compared with a table called name2.
As a side affect, you can now compare tables within a single
database as follows:
```
daff --table name1:name2 db.sqlite db.sqlite
```
The --id flag was until now not respected during sql comparison.
Now it is.  This is particularly useful for comparing tables that
don't have a primary key set.  However, comparisons will be
slower using --id since the database will end up recreating
indexes multiple times rather than just once.
The SQL queries were tweaked a bit to work better without an
index, so that million row comparisons continue to take seconds.
Still, do add an index, you'll be happier.
> make selection of tables and keys more flexible during sql comparison

- .travis.yml
- Makefile
- env/js/fix_exports.js
- env/js/sqlite_database.js
- env/js/util.js
- harness/Main.hx
A change to daff to ease its use with webpack broke its use from a browser via direct script inclusion (#131). This commit makes sure that `exports` is available before fiddling with it.
> do not touch exports without checking that it exists

- package-lock.json
- package.json
Node 10 Dubnium needs fibers 3.x. This PR just bumps fibers from ^1.0.0 to ^3.0.0.
The fibers owner notes that fibers 3 is [a drop-in replacement for earlier versions of fibers](https://github.com/laverdet/node-fibers/issues/379#issuecomment-450544204). The daff tests (`npm test`) with Node 4.9.1 all pass locally for me with fibers@3.1.1.
With the latest Node LTS (currently v10.15.3), `npm install daff` complains with:
```
> fibers@1.0.15 install /home/alice/daff/node_modules/fibers
> node build.js || nodejs build.js
CXX(target) Release/obj.target/fibers/src/fibers.o
../src/fibers.cc:122:64: error: too few arguments to function call, expected at least 3, have 2
return String::NewFromOneByte(isolate, (const uint8_t*)string);
~~~~~~~~~~~~~~~~~~~~~~                                ^ …
```
> Updates `fibers` optional dependency from ^1.0.0 to ^3.0.0

- package.json
Was getting a deprecation warning as part of putting #137 together, which seems to have a fairly straightforward fix:
> Since npm@1.1.71, the npm CLI has run the prepublish script for both npm publish and npm install, because it’s a convenient way to prepare a package for use (some common use cases are described in the section below). It has also turned out to be, in practice, very confusing. As of npm@4.0.0, a new event has been introduced, prepare, that preserves this existing behavior. A new event, prepublishOnly has been added as a transitional strategy to allow users to avoid the confusing behavior of existing npm versions and only run on npm publish (for instance, running the tests one last time to ensure they’re in good shape).
>
>See https://github.com/npm/npm/issues/10074 for a …
> Swaps out the deprecated npm script `prepublish` for `prepublishOnly`

- .travis.yml
- Makefile
- coopy/CombinedTable.hx
- coopy/CombinedTableBody.hx
- coopy/CombinedTableHead.hx
- coopy/JsonTable.hx
- coopy/JsonTables.hx
- coopy/SimpleTable.hx
- coopy/SqlTable.hx
- coopy/SqlTables.hx
- coopy/Table.hx
- coopy/TableIO.hx
- env/php/PhpCellView.php
- env/php/PhpTableView.php
- env/py/sqlite_database.py
- harness/Native.hx
- package-lock.json
- scripts/JavaTableView.java
- scripts/example.php
- test/integration_git.sh
- test/test_sqlite.py
This loads sqlite3 only when needed in python version, so if sqlite3 is absent but unneeded, daff is still usable.
Also includes some tweaks for mac build.
This follows a suggestion by @DerrickRice in #143.
> lazy-load sqlite3 in python

- coopy/Merger.hx
- harness/MergeTest.hx
This commit changes the condition used to detect
conflicts when merging. With this change, if the local and
remote values of a cell match, no conflict is detected and the
local cell value does not change.
> Do nothing with local cell value if local and remote match

- coopy/CompareFlags.hx
- coopy/Coopy.hx
- coopy/TableDiff.hx
- harness/EqualityTest.hx
This applies only to cells outside of the table's primary key.  Requested in #155.
> support an --ignore-epsilon flag that ignores small floating point diffs

- coopy/TableIO.hx
Currently only the js flavor of daff supports --www, and it'd be nice if the python flavor did too (see https://github.com/paulfitz/daff/issues/124#issuecomment-668330346)
> implement --www in python version of daff

- coopy/TableIO.hx
Testing on python2 (still) and python3, this appears to fix the issue in https://github.com/paulfitz/daff/issues/124#issuecomment-668882028
> encode as utf-8 when sending to browser in python

- coopy/Coopy.hx
The other tool I was using until I found this (csvdiff) uses column numbers, and it took me a while to figure out that this one was using names. 🙂
> Clarify that --id and --ignore args take column names

- package.json
This is to allow NPM to build the package from the git repository automatically on `npm install`.
> Add prepare script.

- env/js/util.js
Args are already attached in the loop above, and this line is currently a no-op due to the extra semi-colon.
> Remove unused no-op line

- Makefile
- RELEASE.md
- packaging/java/pom.xml
The project version in the current POM file contains a placeholder that is replaced during Maven's execution. However, Maven repositories read the version from the POM file. 
This PR reads the version from package.json and updates the version in the POM file. Afterwards the build process and the deployment can proceed as usual.
The instructions for deploying, found in RELEASE.md, were correspondingly updated.
> Set the version in the POM file before building the package

- .github/workflows/ci.yml
- coopy/SqlDatabase.hx
- coopy/SqliteHelper.hx
- env/js/sqlite_database.js
- env/js/util.js
- harness/Native.hx
- harness/SqlTest.hx
- package-lock.json
- package.json
- test/test_sqlite.js
The `fiber` dependency in daff.js has always been rather silly. At the time I wrote the node code, `node-sqlite3` was the "standard" for working with sqlite3 in node, but it was async, and hard to integrate with translated code. Now, node has built-in support for sqlite3 on the way, and also `better-sqlite3` is a find sync interface.
Here I rework the node helper files to use `node:sqlite` if available, and `better-sqlite3` if not. I've removed all node dependencies, which I'm not very happy about, but daff sees a lot of use without sqlite3 so it seems bad to be forcing people to install dependencies that include compiled native code.
> prepare to use node:sqlite

- env/js/sqlite_database.js
daff is often used without sqlite, so don't panic unnecessarily.
> js: load sqlite only when needed
